### ISSUE TITLE
brainiak not compatible with osx-arm

### ISSUE THREAD

**Issue by avannucci** [brainiak/brainiak#540] opened 2024-03-06 05:34 UTC
Is it possible to use brainiak with Apple's M1-M3 silicon chips? 

When trying to create a conda environment for brainiak usage, I got the following errors below. Anaconda doesn't seem to have an osx-arm version. How do you recommend I implement? 

Terminal command: conda install -c brainiak -c defaults -c conda-forge brainiak 
                                                                      
Collecting package metadata (current_repodata.json): done                                  
Solving environment: failed with initial frozen solve. Retrying with flexible solve.       
Collecting package metadata (repodata.json): \ WARNING conda.models.version:get_matcher(546): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0                                                                                
WARNING conda.models.version:get_matcher(546): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0                                    
done                  
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - brainiak

Current channels:

  - https://conda.anaconda.org/brainiak/osx-arm64
  - https://conda.anaconda.org/brainiak/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by mihaic** [comment] 2024-03-06 17:48
Hello, @avannucci. Indeed we do not yet provide pre-compiled packages ARM. It should be possible to install from source. There are a couple of prerequisite steps:
https://brainiak.org/docs/installation.html#macos

Alternatively, you could use Docker:
https://brainiak.org/docs/#docker

We are (slowly) setting up the infrastructure to automate releases. Then we intend to publish ARM packages.

**Comment by mihaic** [comment] 2024-03-06 17:49
Duplicate issue #524.

**Comment by mihaic** [comment] 2024-03-06 17:53
Duplicate of #524.

**Closed** 2024-03-06 17:55 UTC
